### ISSUE TITLE
Tips on deployment?

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CIDA/gdp_web#75]
If I wanted to deploy this locally for testing/experimentation, what would the steps be?

**Comment by cschroed-usgs** [comment]
Hi Rich!

Thanks for your interest in running gdp_web. I updated the app's README.md with some instructions. I'm not familiar with your technical background. Apologies in advance if I omitted something important or stated the obvious. How do the instructions work for you?

**Comment by cschroed-usgs** [comment]
Rich,

It turns out my instructions alone are inadequate. There are some additional configuration steps to perform. @mbucknell will likely address these requirements.

**Comment by rsignell-usgs** [comment]
@cschroed-usgs , okay, thanks for the heads up.   I was just about to try it, but was wondering whether certain ports had to be opened.    We already have java 7 and tomcat 7 running.

**Comment by dblodgett-usgs** [comment]
Hi Rich, You will need a number of entries in your context.xml. We will add what these are to the readme when time allows. Mary is off on another project and will get to this next time she works on this one. You aren't in a huge rush to get to this are you?

**Comment by rsignell-usgs** [comment]
No, not in a rush.

**Comment by mbucknell** [comment]
@rsignell-usgs, I have updated the README.md to include the required JNDI variables.
