### ISSUE TITLE
Put example JNDI config in the README.md

### ISSUE THREAD

**Issue by cschroed-usgs** [USGS-CIDA/gdp_web#78]
We would like to fulfill the app configuration requirements for #75. I suggest checking in an example context.xml into the repo and updating the README.md with instructions on how to put the example context.xml on the container.

**Comment by dblodgett-usgs** [comment]
We will add the context.xml lines that need to be in there to the readme with production dependancies to be complete, lets not check in a complete context.xml.

**Comment by cschroed-usgs** [comment]
Well, we definitely shouldn't check in a file called 'context.xml' in the META-INF dir, but why not check in a file called 'exampleContext.xml' with sensible defaults that someone can just copy to their server?

**Comment by jiwalker-usgs** [comment]
There are two things to keep in mind here:
- Checking in the exampleContext.xml can oftentimes be confusing as it gets out of date (mostly on me for lazily forgetting to update it)
- We definitely want to make sure to remove configuration that doesn't specifically apply to this application.  This has been confusing on GDP in the past as the configuration didn't make it clear which application it applied to.

**Comment by mbucknell** [comment]
I prefer putting this kind of information in the README.md. I agree that including an exampleContext.xml frequently gets out of date. Of course it can also get out of date in the README.md, but at least this is something that we frequently see. We have used this successfully on a couple of Flask apps (pubs and wqp).

**Comment by cschroed-usgs** [comment]
@jiwalker-usgs 
> Checking in the exampleContext.xml can oftentimes be confusing as it gets out of date (mostly on me for lazily forgetting to update it)
I agree. I need to point out that it is even more confusing for newcomers, be they internal or external, to have a total absence of example configuration. Starting with an out-of-date document is almost always easier than starting from scratch.

> We definitely want to make sure to remove configuration that doesn't specifically apply to this application. This has been confusing on GDP in the past as the configuration didn't make it clear which application it applied to.
I agree. So far no one suggested checking in irrelevant configuration, but I am glad you reminded us so that we nip that potential problem in the bud. Mixing of concerns has definitely bitten us in the past. Namespacing the jndi var names can help a lot.

**Comment by cschroed-usgs** [comment]
@mbucknell , you raise a great point. I'm sold. Let's stick it in the readme.

**Comment by mbucknell** [comment]
Pull request #79 has been merged, so I'm going to close this issue.
